// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static String _required(String value, String name) {
    if (value.isEmpty) {
      throw StateError('Missing $name (provide via --dart-define=$name=...)');
    }
    return value;
  }

  static String get _webApiKey =>
      _required(const String.fromEnvironment('FIREBASE_WEB_API_KEY'), 'FIREBASE_WEB_API_KEY');
  static String get _androidApiKey => _required(
      const String.fromEnvironment('FIREBASE_ANDROID_API_KEY'), 'FIREBASE_ANDROID_API_KEY');
  static String get _iosApiKey =>
      _required(const String.fromEnvironment('FIREBASE_IOS_API_KEY'), 'FIREBASE_IOS_API_KEY');
  static String get _macosApiKey =>
      _required(const String.fromEnvironment('FIREBASE_MACOS_API_KEY'), 'FIREBASE_MACOS_API_KEY');
  static String get _windowsApiKey => _required(
      const String.fromEnvironment('FIREBASE_WINDOWS_API_KEY'), 'FIREBASE_WINDOWS_API_KEY');

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:576648355848:web:08692d3e8f3909684271bd',
    messagingSenderId: '576648355848',
    projectId: 'pawmilya-flutter',
    authDomain: 'pawmilya-flutter.firebaseapp.com',
    storageBucket: 'pawmilya-flutter.firebasestorage.app',
    measurementId: 'G-TTZR773SBY',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _androidApiKey,
    appId: '1:576648355848:android:acdfe2bf5f9462b74271bd',
    messagingSenderId: '576648355848',
    projectId: 'pawmilya-flutter',
    storageBucket: 'pawmilya-flutter.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _iosApiKey,
    appId: '1:576648355848:ios:773ac71ff3ff80034271bd',
    messagingSenderId: '576648355848',
    projectId: 'pawmilya-flutter',
    storageBucket: 'pawmilya-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterEnchance',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _macosApiKey,
    appId: '1:576648355848:ios:773ac71ff3ff80034271bd',
    messagingSenderId: '576648355848',
    projectId: 'pawmilya-flutter',
    storageBucket: 'pawmilya-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterEnchance',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: _windowsApiKey,
    appId: '1:576648355848:web:3ff1294780f43ddc4271bd',
    messagingSenderId: '576648355848',
    projectId: 'pawmilya-flutter',
    authDomain: 'pawmilya-flutter.firebaseapp.com',
    storageBucket: 'pawmilya-flutter.firebasestorage.app',
    measurementId: 'G-YYPCZTC4FD',
  );
}
